name: Publish Quarto Site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install R Packages
        run: |
          Rscript -e 'install.packages(c("tidyverse", "gt", "nflreadr"))'

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Site
        run: quarto render

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}